import { Legislative } from "../types/legislative";

export const data: Legislative[] = [
  {
    id: "leg-001",
    title: "X Kadencja: Od 2023 roku ",
    content: "Kategoria dotycząca cyfryzacji usług publicznych i transformacji cyfrowej",
    bills: [
      {
        id: "bill-001-1",
        title: "Ustawa o cyfryzacji usług publicznych",
        description: "Jednolite standardy API dla usług administracji",
        status: "uchwalony",
      },
      {
        id: "bill-001-2",
        title: "Prawo podpisu elektronicznego",
        description: "Upowszechnianie podpisu elektronicznego",
        status: "uchwalony",
      },
      {
        id: "bill-001-3",
        title: "Digitalizacja dokumentów",
        description: "Obowiązek digitalizacji dokumentów publicznych",
        status: "sejm",
      },
      {
        id: "bill-001-4",
        title: "API w urzędach",
        description: "Interfejsy API dostępne dla obywateli",
        status: "konsultacje",
      },
      {
        id: "bill-001-5",
        title: "Bezpieczeństwo danych",
        description: "Normy bezpieczeństwa dla usług cyfrowych",
        status: "przed_konsultacjami",
      },
      {
        id: "bill-001-6",
        title: "Portal e-usług",
        description: "Centralna platforma e-usług",
        status: "zapowiedziany",
      },
      {
        id: "bill-001-7",
        title: "Cyberbezpieczeństwo usług publicznych",
        description: "Minimalne wymogi SOC i SIEM dla administracji",
        status: "wstrzymany",
      },
      {
        id: "bill-001-8",
        title: "Dostępność cyfrowa 2.0",
        description: "Nowe standardy WCAG dla usług państwowych",
        status: "sejm",
      },
      {
        id: "bill-001-9",
        title: "eID w sektorze prywatnym",
        description: "Ułatwienia dla integracji eID z usługami komercyjnymi",
        status: "konsultacje",
      },
      {
        id: "bill-001-10",
        title: "Chmura rządowa 2.0",
        description: "Wymogi lokalizacji i szyfrowania danych w chmurze publicznej",
        status: "rada_ministrow",
      },
      {
        id: "bill-001-11",
        title: "Automatyzacja świadczeń",
        description: "Automatyczne przyznawanie świadczeń na podstawie zdarzeń",
        status: "przed_konsultacjami",
      },
    ],
  },
  {
    id: "leg-002",
    title: "IX Kadencja: 2019-2023",
    content: "Kategoria regulacji energetycznych i odnawialnych źródeł energii",
    bills: [
      {
        id: "bill-002-1",
        title: "Nowelizacja prawa energetycznego",
        description: "Gwarancja pochodzenia energii z OZE",
        status: "uchwalony",
      },
      {
        id: "bill-002-2",
        title: "Prosument energii",
        description: "Uproszczone procedury przyłączeniowe",
        status: "sejm",
      },
      {
        id: "bill-002-3",
        title: "Energia słoneczna",
        description: "Wsparcie dla paneli słonecznych",
        status: "konsultacje",
      },
      {
        id: "bill-002-4",
        title: "Energia wiatrowa",
        description: "Regulacje dla farm wiatrowych",
        status: "rada_ministrow",
      },
      {
        id: "bill-002-5",
        title: "Przechowywanie energii",
        description: "Magazynowanie energii odnawialnej",
        status: "przed_konsultacjami",
      },
      {
        id: "bill-002-6",
        title: "Smart grid i licznikowanie",
        description: "Obowiązek inteligentnych liczników do 2030",
        status: "rada_ministrow",
      },
      {
        id: "bill-002-7",
        title: "Kontrakty cPPA dla przemysłu",
        description: "Ułatwienia w długoterminowych umowach na OZE",
        status: "konsultacje",
      },
      {
        id: "bill-002-8",
        title: "Morskie farmy wiatrowe 2",
        description: "Drugi pakiet wsparcia dla offshore",
        status: "sejm",
      },
      {
        id: "bill-002-9",
        title: "Geotermia miejska",
        description: "Program rozwoju ciepłowni geotermalnych",
        status: "konsultacje",
      },
      {
        id: "bill-002-10",
        title: "Magazyny energii domowe",
        description: "Dopłaty do magazynów energii dla gospodarstw domowych",
        status: "zapowiedziany",
      },
    ],
  },
  {
    id: "leg-003",
    title: "VIII Kadencja: 2015-2019",
    content: "Kategoria regulacji sztucznej inteligencji i ochrony danych",
    bills: [
      {
        id: "bill-003-1",
        title: "Ustawa o ochronie danych w AI",
        description: "Wymagania minimalizacji danych w systemach AI",
        status: "konsultacje",
      },
      {
        id: "bill-003-2",
        title: "Rejestr modeli AI",
        description: "Rejestr modeli wysokiego ryzyka",
        status: "konsultacje",
      },
      {
        id: "bill-003-3",
        title: "Przejrzystość algorytmów",
        description: "Obowiązek ujawniania algorytmów decyzyjnych",
        status: "przed_konsultacjami",
      },
      {
        id: "bill-003-4",
        title: "Audyty AI",
        description: "Obowiązkowe audyty systemów AI",
        status: "zapowiedziany",
      },
      {
        id: "bill-003-5",
        title: "Odpowiedzialność AI",
        description: "Odpowiedzialność producentów AI",
        status: "zapowiedziany",
      },
      {
        id: "bill-003-6",
        title: "GDPR i AI",
        description: "Zgodność GDPR z AI",
        status: "wstrzymany",
      },
      {
        id: "bill-003-7",
        title: "Rejestr treningów AI",
        description: "Obowiązek rejestrowania zbiorów treningowych",
        status: "sejm",
      },
      {
        id: "bill-003-8",
        title: "Piaskownica regulacyjna AI",
        description: "Specjalny reżim testowy dla innowacji AI",
        status: "przed_konsultacjami",
      },
      {
        id: "bill-003-9",
        title: "Zarządzanie ryzykiem AI",
        description: "Wymogi dokumentacji i oceny ryzyka modeli",
        status: "sejm",
      },
      {
        id: "bill-003-10",
        title: "Watermarking treści generowanych",
        description: "Obowiązek znakowania treści generowanej przez AI",
        status: "konsultacje",
      },
      {
        id: "bill-003-11",
        title: "Bezpieczeństwo modeli foundation",
        description: "Testy red-teaming i raporty bezpieczeństwa",
        status: "przed_konsultacjami",
      },
    ],
  },
  {
    id: "leg-004",
    title: "VII Kadencja: 2011-2015",
    content: "Kategoria regulacji transportu i mobilności",
    bills: [
      {
        id: "bill-004-1",
        title: "Pojazdy autonomiczne",
        description: "Zasady testów pojazdów autonomicznych",
        status: "sejm",
      },
      {
        id: "bill-004-2",
        title: "Odpowiedzialność operatora",
        description: "Odpowiedzialność operatora pojazdów zdalnych",
        status: "sejm",
      },
      {
        id: "bill-004-3",
        title: "Telemetria pojazdów",
        description: "Wymagania telemetrii dla pojazdów",
        status: "rada_ministrow",
      },
      {
        id: "bill-004-4",
        title: "Bezpieczeństwo transportu",
        description: "Normy bezpieczeństwa transportu",
        status: "konsultacje",
      },
      {
        id: "bill-004-5",
        title: "E-mobilność",
        description: "Wsparcie dla transportu elektrycznego",
        status: "uchwalony",
      },
      {
        id: "bill-004-6",
        title: "Zielone korytarze logistyczne",
        description: "Priorytet dla zeroemisyjnych tras towarowych",
        status: "konsultacje",
      },
      {
        id: "bill-004-7",
        title: "Dynamiczne opłaty drogowe",
        description: "Stawki zależne od emisji i pory dnia",
        status: "sejm",
      },
      {
        id: "bill-004-8",
        title: "Strefy czystego transportu",
        description: "Standardy wjazdu dla miast powyżej 200 tys. mieszkańców",
        status: "rada_ministrow",
      },
      {
        id: "bill-004-9",
        title: "Mikromobilność",
        description: "Regulacje hulajnóg i rowerów współdzielonych",
        status: "sejm",
      },
      {
        id: "bill-004-10",
        title: "Intermodalność kolej-droga",
        description: "Ułatwienia dla transportu kombinowanego",
        status: "konsultacje",
      },
    ],
  },
  {
    id: "leg-005",
    title: "VI Kadencja: 2007-2011",
    content: "Kategoria regulacji dotyczących nauki i badań naukowych",
    bills: [
      {
        id: "bill-005-1",
        title: "Otwarte dane naukowe",
        description: "Deponowanie wyników w repozytoriach open access",
        status: "uchwalony",
      },
      {
        id: "bill-005-2",
        title: "Dostęp do publikacji",
        description: "Wolny dostęp do publikacji naukowych",
        status: "podpis_prezydenta",
      },
      {
        id: "bill-005-3",
        title: "Metadane FAIR",
        description: "Wymogi metadanych FAIR dla badań",
        status: "sejm",
      },
      {
        id: "bill-005-4",
        title: "Finansowanie badań",
        description: "Warunki finansowania badań publicznych",
        status: "konsultacje",
      },
      {
        id: "bill-005-5",
        title: "Infrastruktura badawcza",
        description: "Wspólna infrastruktura badawcza",
        status: "rada_ministrow",
      },
      {
        id: "bill-005-6",
        title: "Transfer technologii",
        description: "Ułatwienia w transferze technologii",
        status: "przed_konsultacjami",
      },
      {
        id: "bill-005-7",
        title: "Chmura dla nauki",
        description: "Wspólna chmura obliczeniowa dla uczelni",
        status: "sejm",
      },
      {
        id: "bill-005-8",
        title: "Granty na dane otwarte",
        description: "Dofinansowanie publikacji zestawów danych",
        status: "przed_konsultacjami",
      },
      {
        id: "bill-005-9",
        title: "Repozytoria narodowe",
        description: "Wspólny standard i finansowanie repozytoriów",
        status: "konsultacje",
      },
      {
        id: "bill-005-10",
        title: "Ewaluacja jakości badań",
        description: "Nowy system oceny dorobku naukowego",
        status: "sejm",
      },
      {
        id: "bill-005-11",
        title: "Mobilność naukowców",
        description: "Stypendia wyjazdowe i powrotne",
        status: "zapowiedziany",
      },
    ],
  },
];
